#ifndef		UI_DEFINE_H_
#define		UI_DEFINE_H_

#define		DEF_UI_COLOR_WHITE			0xFFFFFFFF
#define		DEF_UI_COLOR_RED			0xFF0000FF
#define		DEF_UI_COLOR_YELLOW			0xFFFF00FF
#define		DEF_UI_COLOR_BLUE			0x0000EEFF
#define		DEF_UI_COLOR_GREEN			0x00FF00FF

#define		DEF_UI_COLOR_RAREITEM_NAME	0xFFD31DFF
#define		DEF_UI_COLOR_SET_ITEM		0xCC66FFFF

#define		DEF_UI_COLOR_COOL_BG		0x404040FF
#define		DEF_UI_COLOR_COOL_FRONT		0xDFCFCFFF

#define		DEF_UI_FONT_COLOR			0xF2F2F2FF
#define		DEF_UI_FONT_SHADOW_COLOR	0x181818B2

#define		DEF_UI_COMBO_LIST			0xC5B083FF
#define		DEF_UI_COMBO_LIST_SEL		0xFF6107FF



#define		DEF_DATE_ONE_MIN	60
#define		DEF_DATE_ONE_HOUR	(DEF_DATE_ONE_MIN * 60)
#define		DEF_DATE_ONE_DAY	(DEF_DATE_ONE_HOUR * 24)

// Define button size
#define		BTN_SIZE				32
#define		EVENT_START_INDEX		2000		// 이벤트 인덱스의 시작 위치.
#define		NEWS_WEB				10000		// 웹 공지.
#define		NEWS_NORMAL				10001		// 일반 공지
#define		JEWEL_GRADE_MAX			30

#define		DEF_INI_PATH			"Data\\Etc\\Setting.ini"

#define		JEWEL_POS_CHAOS_SOCKET	0

#define		NAS_INDEX				60000
#define		NAS_TEX_ID				0		
#define		NAS_TEX_ROW				0
#define		NAS_TEX_COL				0

enum eUI_CONTROL
{
	eUI_CONTROL_WINDOW = 0,
	eUI_CONTROL_BASE,
	eUI_CONTROL_IMAGE,
	eUI_CONTROL_BUTTON,
	eUI_CONTROL_TEXT,
		eUI_CONTROL_TEXT_EX,
	eUI_CONTROL_TEXTBOX,
		eUI_CONTROL_TEXTBOX_EX,	// 링크 기능이 추가된 UI_TEXTBOX 확장 컨트롤.
	eUI_CONTROL_EDIT,
	eUI_CONTROL_SCROLL,
	eUI_CONTROL_CHECKBOX,
	eUI_CONTROL_COMBOBOX,
	eUI_CONTROL_SLIDEBAR,
	eUI_CONTROL_PROGRESSBAR,
	eUI_CONTROL_LIST,				// Template 형태의 List 이다. (기존 리스트 대체 가능)
		eUI_CONTROL_LIST_ITEM,	// List 에서 사용하는 템플릿
	eUI_CONTROL_TAB,
		eUI_CONTROL_TABPAGE,
	eUI_CONTROL_ICON,
	eUI_CONTROL_SPINBUTTON,
	eUI_CONTROL_IMAGEFONT,
	eUI_CONTROL_ARRAY,			//
		eUI_CONTROL_ARRAY_ITEM,
	eUI_CONTROL_SPRITEANI,
	eUI_CONTROL_IMAGE_ARRAY,
	eUI_CONTROL_IMAGE_SPLIT,
	eUI_CONTROL_TREE,
		eUI_CONTROL_TREEITEM,
	eUI_CONTROL_SPIN_CONTROL,
	eUI_CONTROL_MAX
};

enum eALIGN_H
{
	eALIGN_H_LEFT = 0,
	eALIGN_H_CENTER,
	eALIGN_H_RIGHT,
};

enum eALIGN_V
{
	eALIGN_V_TOP = 0,
	eALIGN_V_CENTER,
	eALIGN_V_BOTTOM,
};

enum UIMCType
{
	UMCT_NORMAL			= 0,
	UMCT_ATT_NORMAL		= 1,
	UMCT_ATT_SKILL		= 2,
	UMCT_ATT_MAGIC		= 3,
	UMCT_ATT_BOW		= 4,
	UMCT_PICK			= 5,
	UMCT_TALK			= 6,
	UMCT_PRODUCE		= 7,
	UMCT_SIZE			= 8,
	UMCT_ZOOMIN			= 9,
	UMCT_SIGNAL			= 10,
	UMCT_TOTAL			= 11,
	UMCT_CURRENT		= -1,
};

#define LABEL_INDEX_TOTAL 7 //0 도끼, 1 유령, 2 발바닥, 3 조각칼, 4 똥, 5 악마, 6 해골 

enum eNoTransType
{
	TRANS_NAME = 1,
	TRANS_DESC = 2,
	TRANS_DESC2 = 4,
	TRANS_DESC3 = 8,
};

enum UIBtnExType
{
	UBET_SKILL		= 0,
	UBET_ACTION		= 1,
	UBET_ITEM		= 2,
	UBET_QUEST		= 3,
	UBET_EVENT		= 4,
	UBET_REMISSION	= 5,
	UBET_COMBO		= 6,	//ttos: 몬스터 콤보
	UBET_GUILD_MARK,	// [sora] GUILD_MARK
	UBET_TYPE_MAX
};

enum eUIBTN_ETC_TYPE
{
	eETC_TYPE_NONE = 0,
	eETC_TYPE_ITEM,
	eETC_TYPE_NAS,
	eETC_TYPE_EXP,
	eETC_TYPE_SP,
	eETC_TYPE_THEME
};

enum eICON_ATTRIBUTE
{
	eICON_ATTR_NONE = 0,
	eICON_ATTR_FIRE,
	eICON_ATTR_WATER,
	eICON_ATTR_EARTH,
	eICON_ATTR_WIND,
	eICON_ATTR_DARK,
	eICON_ATTR_LIGHT,
	
	eICON_ATTR_MAX,
};

enum eDROPITEM_NAME_COL
{
	eDROPITEM_NORMAL_NAME = 0,
	eDROPITEM_NORMAL_NAME_RARE,
	eDROPITEM_NORMAL_NAME_ORIGIN,
	eDROPITEM_NORMAL_BG,
	eDROPITEM_OVER_NAME,
	eDROPITEM_OVER_NAME_RARE,
	eDROPITEM_OVER_NAME_ORIGIN,
	eDROPITEM_OVER_BG,

	eDROPITEM_NAME_COL_MAX
};
#endif		// UI_DEFINE_H_