//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SeriousSkaStudio.rc
//
#define IDC_TB_COLHEIGHT                2
#define IDD_ABOUTBOX                    100
#define IDW_TOOLBAR_MAINFRAME           101
#define IDW_TOOLBAR_NAVIGATION          102
#define IDW_TOOLBAR_MANAGE              103
#define IDR_MAINFRAME                   128
#define IDR_SERIOUTYPE                  129
#define IDR_NAVIGATION                  130
#define IDD_TREEBAR                     137
#define IDB_BITMAP1                     138
#define IDR_MANAGE                      139
#define IDD_PARENT                      141
#define IDD_COLISION                    142
#define IDD_ANIMSET                     143
#define IDD_LOD                         144
#define IDD_SHADER                      145
#define IDD_TEXTURE                     146
#define IDD_LIST_OPTIONS                147
#define IDD_ERROR_LIST                  148
#define IDD_ALL_FRAMES_BBOX             149
#define IDR_POPUP_MENU                  151
#define IDD_BONE                        152
#define IDD_CONVERT_RECURSIVE           153
#define IDD_PROPERTIES                  154
#define IDD_SKATAG                      155
#define IDD_EFFECT_EDIT                 157
#define IDD_CEFFECT_PROPERTY            158
#define IDD_CLIGHTEFFECT_PROPERTY       160
#define IDD_CMDLEFFECT_PROPERTY         162
#define IDD_CSKAEFFECT_PROPERTY         163
#define IDD_CTERRAINEFFECT_PROPERTY     164
#define IDD_CSOUNDEFFECT_PROPERTY       166
#define IDD_CTRACEEFFECT_PROPERTY       167
#define IDD_EFFECT_EDIT_TYPE            168
#define IDD_CEFFECTGROUP_PROPERTY       169
#define IDD_CPARTICLEGROUP_PROPERTY     170
#define IDD_CPARTICLEEFFECT_PROPERTY    171
#define IDD_EE_SCROLLBAR                172
#define IDD_CPARTICLEEMITTER_PROPERTY   173
#define IDD_CPE_SPHERE_PROPERTY         174
#define IDD_FORCE                       175
#define IDD_SPHERE                      176
#define IDD_CPARTICLEABSORPTION_PROPERTY 177
#define IDD_CPARTICLEPROCESS_PROPERTY   178
#define IDD_CPP_FORCE_PROCESS_PROPERTY  179
#define IDD_CPP_DYNAMICSTATE_PROPERTY   180
#define IDD_CPA_SPHERE_PROPERTY         181
#define IDD_CPP_POINTGOAL_PROPERTY      182
#define IDD_CONE                        185
#define IDD_CYLINDER                    186
#define IDD_CPE_CONE_PROPERTY           187
#define IDD_CPE_CYLINDER_PROPERTY       188
#define IDD_CPA_DEFAULT_PROPERTY        189
#define IDD_CPP_CONTROL_PROPERTY        190
#define IDD_CEFFECTCONTROL_PROPERTY     191
#define IDD_CSPLINEBILLBOARDEFFECT_PROPERTY 193
#define IDD_CPP_DS_OFFSETPOS_AUTOSETTING 194
#define IDD_AUTOSETTING_FEATHER_FALL    195
#define IDD_ANIMEFFECT                  196
#define IDD_CPP_VELOCITY_PROCESS_PROPERTY 197
#define IDD_CORBITEFFECT_PROPERTY       198
#define IDD_CSHOCKWAVEEFFECT_PROPERTY   199
#define IDD_CSPLINEPATHEFFECT_PROPERTY  200
#define IDD_CFOLLOWEFFECT_PROPERTY      201
#define IDD_CCAMERAEFFECT_PROPERTY      202
#define IDD_CENTITYEFFECT_PROPERTY      203
#define IDD_DLG_EXTENSION               204
#define IDD_RIDESET                     205
#define IDC_TREE1                       1000
#define IDC_SELECTEDMI                  1003
#define IDC_CB_PARENTBONE               1004
#define IDC_CB_PARENTMODEL              1005
#define IDC_PBONE_LAB                   1006
#define IDC_PMODEL_LAB                  1007
#define IDC_OFF_POSX                    1008
#define IDC_OFF_POSY                    1009
#define IDC_OFF_POSZ                    1010
#define IDC_OFF_ROTH                    1011
#define IDC_OFF_ROTP                    1012
#define IDC_OFF_ROTB                    1013
#define IDC_OFF_POSLABEL                1014
#define IDC_OFF_ROTLABEL                1015
#define IDC_CB_TEXNAME                  1016
#define IDC_LB_TEX_NAME                 1017
#define IDC_MODE_SELECT_TAB             1018
#define IDC_EB_DISTANCE                 1019
#define IDC_LB_DISTANCE_FAC             1020
#define IDC_EB_TRESHOLD                 1021
#define IDC_LB_TRESHOLD                 1022
#define IDC_CB_COMPRESION               1023
#define IDC_TB_COLWIDTH                 1024
#define IDC_TB_COLPOSX                  1025
#define IDC_TB_COLLENGTH                1026
#define IDC_LB_COLNAME                  1027
#define IDC_TB_COLPOSY                  1028
#define IDC_LB_BONE_NAME                1028
#define IDC_TB_COLPOSZ                  1029
#define IDC_LB_WHL                      1030
#define IDC_LB_XYZ                      1031
#define IDC_EB_SECPERFRAME              1032
#define IDC_LB_POSX                     1032
#define IDC_LB_SECPERFRAME              1033
#define IDC_CB_SHADER                   1033
#define IDC_LB_POSY                     1033
#define IDC_TB_COLNAME                  1034
#define IDC_LB_POSZ                     1034
#define IDC_TB_WALKSPEED                1035
#define IDC_TB_ZTRANSSPEED              1035
#define IDC_LB_HEADING                  1035
#define IDC_TB_WALKLOOP                 1036
#define IDC_TB_ZTRANSLOOP               1036
#define IDC_LB_PITCH                    1036
#define IDC_LB_ZTRANSLOOP               1037
#define IDC_LB_BANKING                  1037
#define IDC_LB_ZTRANSSPEED              1038
#define IDC_CB_SECPERFRAME              1039
#define IDC_SPLITER_FRAME2              1041
#define IDC_TB_GAPI                     1041
#define IDC_LB_PARENTBONE               1046
#define IDC_LB_PARENT_MODEL             1047
#define IDC_LB_OFFSET_POS               1048
#define IDC_LB_OFFSET_ROT               1049
#define IDC_TB_OFFSET_POSX              1050
#define IDC_TB_OFFSET_POSY              1051
#define IDC_TB_OFFSET_POSZ              1052
#define IDC_TB_OFFSET_ROTH              1053
#define IDC_TB_OFFSET_ROTP              1054
#define IDC_TB_OFFSET_ROTB              1055
#define IDC_LB_PARENT_MODEL2            1056
#define IDC_LB_SHADER_NAME              1061
#define IDC_LB_TEXTURE_NAME             1062
#define IDC_EB_TEXTURENAME              1063
#define IDC_TEXTURE_VIEW                1064
#define IDC_BT_DUMMYCOLOR               1065
#define IDC_BT_CONVERT                  1066
#define IDC_BT_RELOAD_TEXTURE           1067
#define IDC_BT_RECREATE_TEXTURE         1068
#define IDC_BT_CLOSE                    1068
#define IDC_BT_CLEAR                    1069
#define IDC_BT_BROWSE_TEXTURE           1069
#define IDC_LC_ERROR_LIST               1070
#define IDC_SPLITER_LOG_FRAME           1071
#define IDC_SPLITER_FRAME               1072
#define IDC_SPLITTER_TREE               1078
#define IDC_BT_RESET_COLISION           1080
#define IDC_BT_RESET_OFFSET             1081
#define IDC_TB_MI_NAME                  1082
#define IDC_BT_CALC_ALLFRAMES_BBOX      1083
#define IDC_LB_BONENAME_LABEL           1084
#define IDC_LB_HPB                      1086
#define IDC_FILE_BEING_CONVERTED        1089
#define IDC_CONVERSION_PROGRESS         1092
#define IDC_ELAPSED_TIME                1093
#define IDC_ESTIMATED_TIME              1094
#define IDC_LISTS_CONVERTED             1095
#define IDC_TB_FOV                      1095
#define IDC_SKATAG_NAME                 1096
#define IDC_SKATAG_OFFSETPOSX           1097
#define IDC_SKATAG_OFFSETPOSY           1098
#define IDC_SKATAG_OFFSETPOSZ           1099
#define IDC_SKATAG_OFFSETROTAXISX       1100
#define IDC_SKATAG_OFFSETROTAXISY       1101
#define IDC_SKATAG_OFFSETROTAXISZ       1102
#define IDC_SKATAG_OFFSETROTANGLE       1103
#define IDC_SKATAG_PARENTBONE1          1104
#define IDC_SKATAG_PARENTBONE2          1105
#define IDC_SKATAG_PARENTBONE3          1106
#define IDC_SKATAG_PARENTBONE4          1107
#define IDC_EE_TYPE                     1107
#define IDC_SKATAG_BLENDFACTOR4         1108
#define IDC_EE_REGISTERED_NAME          1108
#define IDC_SKATAG_BLENDFACTOR3         1109
#define IDC_PG_BLEND_TYPE               1109
#define IDC_SKATAG_BLENDFACTOR2         1110
#define IDC_SKATAG_BLENDFACTOR1         1111
#define IDC_BTN_DEL                     1112
#define IDC_BTN_SAVE                    1113
#define IDC_BTN_POSLIST_DEL             1113
#define IDC_EFFECT_NAME                 1114
#define IDC_BTN_EK_DEL                  1114
#define IDC_BTN_UP                      1114
#define IDC_LIFE_TIME                   1115
#define IDC_BTN_EK_ADD                  1115
#define IDC_BTN_DOWN                    1115
#define IDC_REPEAT_COUNT                1116
#define IDC_FALL_OFF                    1116
#define IDC_BTN_TK_DEL                  1116
#define IDC_FADE_IN_TIME                1117
#define IDC_BTN_TK_ADD                  1117
#define IDC_FADE_OUT_TIME               1118
#define IDC_BTN_LIGHT_COLOR             1118
#define IDC_EK_START_TIME               1118
#define IDC_CHECK_AMBIENT_MODE          1119
#define IDC_EK_SETTING_TIME             1119
#define IDC_TWINKLE_PERIOD              1119
#define IDC_BOUNDING_SPHERE_RADIUS      1119
#define IDC_MDL_FILENAME                1120
#define IDC_BTN_REFRESH                 1120
#define IDC_VELOCITY                    1120
#define IDC_BTN_MDL_FILEFIND            1121
#define IDC_BTN_TK_ADDALL               1121
#define IDC_MDL_TEX_FILENAME            1122
#define IDC_SKA_FILENAME                1122
#define IDC_BTN_MDL_TEX_FILEFIND        1123
#define IDC_BTN_SKA_FILEFIND            1123
#define IDC_TRAREA_LEFT                 1124
#define IDC_TRAREA_TOP                  1125
#define IDC_TRAREA_RIGHT                1126
#define IDC_TRAREA_BOTTOM               1127
#define IDC_BTN_TRCOLOR                 1128
#define IDC_BTN_TRACE_END_COLOR         1129
#define IDC_SND_FLAGS                   1131
#define IDC_SND_FALLOFF                 1132
#define IDC_SND_HOTSPOT                 1133
#define IDC_SND_VOLUME                  1134
#define IDC_SND_PITCH                   1135
#define IDC_BTN_SND_FILEFIND            1136
#define IDC_SND_FILENAME                1137
#define IDC_TERRAIN_FILENAME            1138
#define IDC_BTN_TERRAIN_FILEFIND        1139
#define IDC_TRACE_FILENAME              1140
#define IDC_BTN_TRACE_FILEFIND          1141
#define IDC_TRACE_TIME                  1142
#define IDC_TRACE_INTERVAL              1143
#define IDC_WIDTH                       1143
#define IDC_ED_PHASEMULX                1143
#define IDC_BTN_TRACE_BEGIN_COLOR       1144
#define IDC_ED_PHASEOFFSETX             1144
#define IDC_TRACE_TWINKLE_PERIOD        1145
#define IDC_ED_RADIUSY                  1145
#define IDC_ED_PHASEMULY                1146
#define IDC_CB_EFFECT_EDIT_TYPE         1147
#define IDC_ED_PHASEOFFSETY             1147
#define IDC_EG_NAME                     1148
#define IDC_ED_RADIUSZ                  1148
#define IDC_REGISTERED_EFFECT_KEY       1149
#define IDC_ED_PHASEMULZ                1149
#define IDC_REGISTERED_EFFECT_FOR_EK    1150
#define IDC_ED_PHASEOFFSETZ             1150
#define IDC_REGISTERED_TAG_KEY          1151
#define IDC_ED_TIMEBEFORESTART          1151
#define IDC_TAG_NAME_FOR_TAG_KEY        1152
#define IDC_ED_GOALTAG                  1152
#define IDC_EG_REGISTERED_NAME          1153
#define IDC_ED_OFFSETX                  1153
#define IDC_PE_REGISTERED_PARTICLE_GROUP 1154
#define IDC_ED_OFFSETY                  1154
#define IDC_EFFECT_TYPE                 1154
#define IDC_ED_OFFSETZ                  1155
#define IDC_REGISTERED_TAG_NAME         1155
#define IDC_ED_FADEIN_RMUL              1156
#define IDC_EE_SCROLLBAR                1157
#define IDC_ED_FADEIN_PMUL              1157
#define IDC_TAB_PG_COMPONENT            1158
#define IDC_ED_FADEOUT_RMUL             1158
#define IDC_ED_FADEOUT_PMUL             1159
#define IDC_PG_REGISTERED_NAME          1160
#define IDC_PG_NAME                     1161
#define IDC_PG_RENDER_TYPE              1162
#define IDC_PG_TEX_FILENAME             1163
#define IDC_BTN_PG_TEX_FILEFIND         1164
#define IDC_PG_MEXWIDTH                 1165
#define IDC_PG_MEXHEIGHT                1166
#define IDC_PG_COLUMN                   1167
#define IDC_PG_ROW                      1168
#define IDC_EMITTER_TYPE                1169
#define IDC_EMITTER_MAXCOUNT            1170
#define IDC_EMITTER_EMITSPEED           1171
#define IDC_EMITTER_LIFETIME2           1172
#define IDC_EMITTER_LIFETIME1           1173
#define IDC_FORCE_X                     1174
#define IDC_BTN_COLOR1                  1181
#define IDC_EMITTER_WIDTH2              1182
#define IDC_EMITTER_WIDTH1              1183
#define IDC_FORCE_NORMALIZE             1183
#define IDC_EMITTER_MASS2               1184
#define IDC_FORCE_POWER                 1184
#define IDC_EMITTER_MASS1               1185
#define IDC_FORCE_Y                     1185
#define IDC_FORCE_Z                     1186
#define IDC_BTN_COLOR2                  1186
#define IDC_EMITTER_HEIGHT2             1187
#define IDC_FORCE_TYPE                  1187
#define IDC_SPHERE_OUTER_RADIUS         1187
#define IDC_EMITTER_HEIGHT1             1188
#define IDC_BTN_FORCE                   1188
#define IDC_BTN_SPHERE                  1189
#define IDC_BTN_MODIFY                  1189
#define IDC_EMITTER_ANGLEY1             1189
#define IDC_EMITTER_DELAYTIME           1190
#define IDC_EMITTER_ANGLEZ1             1190
#define IDC_SPHERE_X                    1191
#define IDC_PECONE_SPEED_UPPER          1191
#define IDC_EMITTER_ANGLEX1             1191
#define IDC_SPHERE_Y                    1192
#define IDC_EMITTER_ANGLEY2             1192
#define IDC_SPHERE_Z                    1193
#define IDC_EMITTER_ANGLEZ2             1193
#define IDC_SPHERE_INNER_RADIUS         1194
#define IDC_EMITTER_ANGLEX2             1194
#define IDC_ABSORPTION_TYPE             1195
#define IDC_PARTICLE_MOVE_TYPE          1196
#define IDC_PP_TYPE                     1197
#define IDC_BTN_ADD                     1198
#define IDC_PP_ADDED                    1199
#define IDC_BTN_POSLIST_ADD             1199
#define IDC_LIST_FORCE                  1200
#define IDC_TAB_STATE_COMPONENT         1201
#define IDC_LIST_ADDED_STATE            1202
#define IDC_CHK_COMBINE_COLOR           1203
#define IDC_RANDOM                      1204
#define IDC_STATIC_STATE_NAME           1205
#define IDC_VALUE1                      1206
#define IDC_VALUE2                      1207
#define IDC_BTN_COLOR                   1208
#define IDC_BTN_TEST_EFFECTSYSTEM       1209
#define IDC_VALUE3                      1209
#define IDC_ADD_TIME                    1210
#define IDC_CHK_DEPENDLIFE              1211
#define IDC_STATIC_INNER                1213
#define IDC_STATIC_OUTER                1214
#define IDC_POINTGOAL_X                 1215
#define IDC_POINTGOAL_Y                 1216
#define IDC_POINTGOAL_Z                 1217
#define IDC_POINTGOAL_SPEED             1218
#define IDC_POINTGOAL_LERPRATIO         1219
#define IDC_CONE_HEIGHT                 1220
#define IDC_CONE_HEIGHT_UPPER           1220
#define IDC_CONE_FALLOFF_ANGLE          1221
#define IDC_POINTGOAL_LERPSPEED         1221
#define IDC_CONE_HOTSPOT_ANGLE          1222
#define IDC_CONTROL_HEIGHTSPEED         1222
#define IDC_POINTGOAL_GOALTAGNAME       1222
#define IDC_CONE_X                      1223
#define IDC_CONE_Y                      1224
#define IDC_CONE_Z                      1225
#define IDC_CYLINDER_X                  1226
#define IDC_CONE_HEIGHT_LOWER           1226
#define IDC_CYLINDER_Y                  1227
#define IDC_CONE_CLOSE_RANGE            1227
#define IDC_CYLINDER_Z                  1228
#define IDC_CONE_LERP_RATIO             1228
#define IDC_CYLINDER_HEIGHT             1229
#define IDC_STATIC_HOTSPOT              1230
#define IDC_STATIC_FALLOFF              1231
#define IDC_CYLINDER_INNER_RADIUS       1232
#define IDC_CYLINDER_OUTER_RADIUS       1233
#define IDC_PECONE_CHK_POS              1234
#define IDC_PECONE_CHK_SPEED            1235
#define IDC_PECONE_BTN_CONE             1236
#define IDC_PECONE_SPEED_LOWER          1237
#define IDC_PECYL_SPEED_LOWER           1238
#define IDC_PECYL_SPEED_UPPER           1239
#define IDC_PECYL_CHK_POS               1240
#define IDC_PECYL_CHK_SPEED             1241
#define IDC_PECYL_BTN_CYLINDER          1242
#define IDC_BTN_MDL_COLOR               1243
#define IDC_PECYL_CHK_EMITALLDIR        1243
#define IDC_MDL_STRETCH_X               1244
#define IDC_MDL_STRETCH_Y               1245
#define IDC_MDL_STRETCH_Z               1246
#define IDC_BTN_SKA_COLOR               1247
#define IDC_SKA_STRETCH_X               1248
#define IDC_SKA_STRETCH_Y               1249
#define IDC_SKA_STRETCH_Z               1250
#define IDC_CHK_DEPEND_LIFE             1251
#define IDC_TE_BLEND_TYPE               1252
#define IDC_BTN_AUTOSETTING             1253
#define IDC_BTN_TEMP                    1254
#define IDC_BTN_TEMP2                   1255
#define IDC_CONTROL_TYPE                1256
#define IDC_CONTROL_ANGLESPEED          1259
#define IDC_STATIC_HEIGHTSPEED          1260
#define IDC_CHK_CONTROL_USE_POSITION    1261
#define IDC_CHK_EFFECT_CONTROL          1262
#define IDC_COMBO_ROTATION_TYPE         1263
#define IDC_FILENAME                    1264
#define IDC_CHK_OVERDRAW                1264
#define IDC_COMBO_POSITION_TYPE         1264
#define IDC_BTN_FILEFIND                1265
#define IDC_CB_POSITION_TYPE            1265
#define IDC_INTERVAL                    1267
#define IDC_BTN_SBB_COLOR_BEGIN         1268
#define IDC_BTN_COLOR_BEGIN             1268
#define IDC_BTN_SBB_COLOR_END           1269
#define IDC_BTN_COLOR_END               1269
#define IDC_CHK_CAPEND                  1270
#define IDC_CB_TYPE                     1271
#define IDC_EDIT_WIDTH                  1272
#define IDC_EDIT_LENGTH                 1273
#define IDC_ANIMEFFECT_EFFECTGROUPNAME  1273
#define IDC_EDIT_HEIGHT                 1274
#define IDC_ANIMEFFECT_STARTTIME        1274
#define IDC_ANIMEFFECT_ANIMNAME         1275
#define IDC_EDIT_REPEAT                 1276
#define IDC_ANIMEFFECT_FLAGS            1276
#define IDC_EDIT_PERIOD                 1277
#define IDC_VELOCITY_SPEED              1277
#define IDC_VELOCITY_DIRX               1278
#define IDC_VELOCITY_DIRY               1279
#define IDC_COMBO_ORBIT_LIST            1279
#define IDC_VELOCITY_DIRZ               1280
#define IDC_COMBO_SPLINE_LIST           1282
#define IDC_ED_RADIUSX                  1284
#define IDC_LIST_FADEIN_FLAG            1285
#define IDC_ED_TIME                     1285
#define IDC_LIST_FADEOUT_FLAG           1286
#define IDC_SHOCKWAVE_FILENAME          1286
#define IDC_CHECK_OUTERBASIS            1287
#define IDC_SHOCKWAVE_SPLITCOUNT        1288
#define IDC_SHOCKWAVE_RADIUSADD         1289
#define IDC_SHOCKWAVE_RADIUSVALUE       1290
#define IDC_SHOCKWAVE_RADIUSMODIFY      1291
#define IDC_SHOCKWAVE_RADIUSDELETE      1292
#define IDC_SHOCKWAVE_WIDTHADD          1294
#define IDC_SHOCKWAVE_WIDTHMODIFY       1295
#define IDC_SHOCKWAVE_WIDTHDELETE       1296
#define IDC_SHOCKWAVE_ANGLEADD          1298
#define IDC_SHOCKWAVE_ANGLEMODIFY       1299
#define IDC_SHOCKWAVE_ANGLEDELETE       1300
#define IDC_SHOCKWAVE_RADIUSLIST        1301
#define IDC_SHOCKWAVE_WIDTHLIST         1302
#define IDC_SHOCKWAVE_ANGLELIST         1303
#define IDC_SHOCKWAVE_FILEFIND          1304
#define IDC_SHOCKWAVE_RADIUSTIME        1305
#define IDC_SHOCKWAVE_WIDTHVALUE        1306
#define IDC_SHOCKWAVE_WIDTHTIME         1307
#define IDC_SHOCKWAVE_ANGLEVALUE        1308
#define IDC_SHOCKWAVE_ANGLETIME         1309
#define IDC_BLEND_TYPE                  1310
#define IDC_LIST_POS                    1312
#define IDC_CHECK_DIRECTAPPLY           1313
#define IDC_COMBO_EFFECT_LIST           1314
#define IDC_ED_POSZ                     1315
#define IDC_ED_POSY                     1316
#define IDC_ED_POSX                     1317
#define IDC_COMBO_LIST                  1318
#define IDC_CHECK_LOCALTYPE             1320
#define IDC_OFFSET_X                    1321
#define IDC_OFFSET_Y                    1322
#define IDC_OFFSET_Z                    1323
#define IDC_ED_WIDTH                    1324
#define IDC_ED_HEIGHT                   1325
#define IDC_ED_TWIST                    1326
#define IDC_BTN_LIST_ADDMOD             1327
#define IDC_BTN_LIST_DEL                1328
#define IDC_LIST                        1329
#define IDC_ED_ZOOM                     1330
#define IDC_BTN_EXTENSION               1330
#define IDC_ED_MOVEX                    1331
#define IDC_EDIT_TOTAL_TIME_RATIO       1331
#define IDC_ED_MOVEY                    1332
#define IDC_BTN_TOTAL_TIME_RATIO_APPLY  1332
#define IDC_ED_MOVEZ                    1333
#define IDC_CB_RIDE_PARENTBONE          1333
#define IDC_TB_RIDE_OFFSET_POSX         1334
#define IDC_TB_RIDE_OFFSET_POSY         1335
#define IDC_TB_RIDE_OFFSET_POSZ         1336
#define IDC_TB_RIDE_OFFSET_ROTH         1337
#define IDC_TB_RIDE_OFFSET_ROTP         1338
#define IDC_TB_RIDE_OFFSET_ROTB         1339
#define IDC_LB_RIDE_OFFSET_POS          1341
#define IDC_LB_RIDE_OFFSET_ROT          1342
#define IDC_LB_RIDE_PARENTBONE          1343
#define ID_TEXTURE_OPEN                 32771
#define ID_RESET_VIEW                   32772
#define ID_IMPORT_ASCIIFILE             32774
#define ID_IMPORT_SKELETON              32775
#define ID_IMPORT_ANIMSET               32776
#define ID_SHOW_WIREFRAME               32777
#define ID_SHOW_SKELETON                32778
#define ID_SHOW_TEXTURE                 32779
#define ID_IMPORT_SMCSCRIPT             32780
#define ID_IMPORT_CONVERT               32784
#define ID_VIEW_TREEVIEW                32787
#define ID_ADD_MODEL_INSTANCE           32790
#define ID_ADD_MESHLOD                  32791
#define ID_ADD_SKELETONLOD              32792
#define ID_ADD_ANIMATION                32793
#define ID_DELETESELECTED               32794
#define ID_ADD_MESHLIST                 32795
#define ID_ADD_SKELETONLIST             32797
#define ID_ADD_ANIMSET                  32798
#define ID_ADD_TEXTURE                  32799
#define ID_ADD_CHILD_MODEL_INSTANCE     32800
#define ID_SHOW_WEIGHTS                 32801
#define ID_ADD_COLISIONBOX              32802
#define ID_ANIM_STOP                    32803
#define ID_ANIM_SYNC                    32804
#define ID_AUTO_MIPING                  32806
#define ID_SHOW_GROUND                  32807
#define ID_SHOW_ANIM_QUEUE              32809
#define ID_FILE_SAVEMI                  32812
#define ID_SHOW_NORMALS                 32813
#define ID_SHOW_LIGHTS                  32814
#define ID_CHANGE_AMBIENT               32815
#define ID_CHANGE_LIGHTCOLOR            32816
#define ID_CHANGE_AMBIENTCOLOR          32817
#define ID_ANIM_LOOP                    32818
#define ID_ANIM_PAUSE                   32819
#define ID_SHOW_COLISION                32820
#define ID_FILE_CREATETEXTURE           32821
#define ID_FILE_CREATE_TEXTURE          32822
#define ID_FILE_X                       32823
#define ID_FILE_SAVEMI_AS               32824
#define ID_FILE_RECREATETEXTURE         32825
#define ID_VK_UP                        32826
#define ID_VK_DOWN                      32827
#define ID_VIEW_ERRORLIST               32828
#define ID_VK_ESCAPE                    32829
#define ID_CREATE_ADD_TEXTURE           32830
#define ID_ADD_ALLFRAMES_BBOX           32831
#define ID_ADD_TEXTURE_SPECULAR         32832
#define ID_ADD_TEXTURE_BUMP             32833
#define ID_ADD_TEXTURE_REFLECTION       32834
#define ID_SHOW_ACTIVE_SKELETON         32835
#define ID_SHOW_ALL_FRAMES_BBOX         32836
#define ID_CONVERT_SELECTED             32839
#define ID_ALL_FRAMES_RECALC            32840
#define ID_ANIMATION_PLAY               32841
#define ID_MODELINSTANCE_SAVEWITHOFFSET 32842
#define ID_VK_LEFT                      32843
#define ID_VK_RIGHT                     32844
#define ID_VK_LEFT_WITH_CTRL            32845
#define ID_VK_RIGHT_WITH_CTRL           32846
#define ID_BBOX_RESET                   32847
#define ID_RESET_COLISIONBOX            32848
#define ID_RELOAD_TEXTURE               32849
#define ID_RECREATE_TEXTURE             32850
#define ID_BROWSE_TEXTURE               32851
#define ID_MI_STRETCH                   32853
#define ID_MEASURE_TOOL                 32854
#define ID_ROTATE_VIEWER                32855
#define ID_ROTATE_LIGHT                 32856
#define ID_INCREMENT_FADE_TIME          32857
#define ID_DECREMENT_FADE_TIME          32858
#define ID_FREEZE_ON_BLEND              32859
#define ID_CONVERT_RECURSIVE            32860
#define ID_COUNT_WEIGHT_PER_VERTEX      32861
#define ID_INCREMENT_BPV                32862
#define ID_DECREMENT_BPV                32863
#define ID_USE_HARDWARE_VP              32864
#define ID_USE_SOFTWARE_VP              32865
#define ID_VK_CTRL1                     32866
#define ID_VK_CTRL2                     32867
#define ID_VK_CTRL3                     32868
#define ID_VK_CTRL4                     32869
#define ID_VK_CTRL5                     32870
#define ID_VK_CTRL6                     32871
#define ID_VK_CTRL7                     32872
#define ID_VK_CTRL8                     32873
#define ID_VK_CTRL9                     32874
#define ID_VK_CTRL0                     32875
#define ID_VK_CTRL_INSERT               32877
#define ID_VK_CTRL_DELETE               32878
#define ID_CONVERT_TEXTURERECURSIVE     32881
#define ID_PRERERENCES                  32883
#define ID_SHOW_SUBSURFACES             32884
#define ID_VK_Z                         32885
#define ID_SHOW_AXIS                    32886
#define ID_SHOWALL_EVENTS               32887
#define ID_PROFILING                    32888
#define ID_SHOW_FPS                     32889
#define ID_SHOWPROJECTIONSHADOW         32890
#define ID_REFRESH_TAGMANAGER           32892
#define ID_SKATAG_NEW                   32893
#define ID_SKATAG_DELETE                32894
#define ID_SHOW_EFFECT                  32895
#define ID_VIEW_EFFECT_EDIT             32896
#define ID_EFFECT_OPEN                  32897
#define ID_EFFECT_SAVE                  32898
#define ID_EFFECT_RESET                 32899
#define ID_EFFECT_REFRESH               32900
#define ID_EFFECT_SAVEAS                32901
#define ID_ANIM_FORWARD_ONE_TICK        32902
#define ID_ANIMEFFECT_REG_ADDNEW        32903
#define ID_ANIMATION_EFFECT_ADD         32905
#define ID_FILE_CONVERTALL              32907
#define ID_EFFECT_OPEN_AS_ADD           32908
#define ID_FILE_EXPORT_TEXTURE          32909
#define ID_MI_ALPHA                     32910
#define ID_ANIM_STRENGTH_UP             32911
#define ID_ANIM_STRENGTH_DOWN           32912
#define ID_EFFECT_EXPORT_INFO_FILE      32913
#define ID_MI_GROUNDCOLOR               32917
#define ID_MI_AIRCOLOR                  32918
#define ID_EFFECT_AUTO_SPELL            32919
#define ID_VK_TAB                       32920
#define ID_VK_SHIFT_TAB                 -32615
#define ID_CONVERT_THUMBNAIL            32922
#define ID_CREATEITEMDATA               32923
#define ID_RIDESETTING                  32924
#define ID_STATUS_BAR_TEXT              61216
#define ID_VIEW_DLG_PREFS               61217

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32925
#define _APS_NEXT_CONTROL_VALUE         1345
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
